name: Generate Docker Compose Diagram

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.yml'
  workflow_dispatch:

jobs:
  generate_diagram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create output directory
      run: |
        mkdir -p diagrams

    - name: Generate GUID
      id: gen_guid
      run: |
        guid=$(uuidgen)
        echo "GUID=$guid" >> $GITHUB_ENV

    - name: Generate Docker Compose diagram
      run: |
        docker run --rm --user $(id -u):$(id -g) --name dcv -v ${{ github.workspace }}/docker-compose.yml:/input/docker-compose.yml -v ${{ github.workspace }}/diagrams:/output pmsipilot/docker-compose-viz render -m image -o /output/${{ env.GUID }}.png

    - name: Print Docker container logs
      run: |
        docker logs dcv 2>&1 || true

    - name: List output directory contents
      run: |
        ls -la diagrams

    - name: Commit the generated diagram and create a pull request
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b "generated-diagram-${{ env.GUID }}"
        git add diagrams/${{ env.GUID }}.png
        git commit -m "Generated Docker Compose diagram"
        git push --set-upstream origin "generated-diagram-${{ env.GUID }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
