name: Generate Docker Compose Diagram

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.yml'
  workflow_dispatch:

jobs:
  generate_diagram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create output directory
      run: |
        mkdir -p diagrams

    - name: Generate GUID
      id: guid
      run: |
        echo "::set-output name=guid::$(uuidgen)"
    
    - name: Generate Docker Compose diagram
      run: |
        docker run --rm --name dcv -v ${{ github.workspace }}/docker-compose.yml:/input/docker-compose.yml -v ${{ github.workspace }}/diagrams:/output pmsipilot/docker-compose-viz render -m image -o /output/${{ steps.guid.outputs.guid }}.png

    - name: List output directory contents
      run: |
        ls -la diagrams

    - name: Commit and push the generated diagram
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add diagrams/${{ steps.guid.outputs.guid }}.png
        git commit -m "Generated Docker Compose diagram" -a
        git push
